name: Linux CI

on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install .

      - name: Install dev requirements
        run: python -m pip install -r requirements-dev.txt

      - name: pytest
        run: python -m pytest tests

  qa:
    name: Quality Checks
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-ci.txt

      - name: flake8 check
        run: |
          flake8 envee

      - name: Mypy check
        run: |
          mypy --strict envee

  # Merge dependabot PRs if quality check succeed
  dependabot:
    name: "Dependabot"
    needs: [test, qa]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}